export const fakeGpus = [
  {
    id: 'fake-3060',
    name: 'NVIDIA GeForce RTX 3060',
    vram_gb: 12,
    price_per_hour: 2,
    status: 'unavailable',
    image: '/images/gpus/rtx3060.jpg',
  },
  {
    id: 'fake-3070',
    name: 'NVIDIA GeForce RTX 3070',
    vram_gb: 8,
    price_per_hour: 2,
    status: 'unavailable',
    image: '/images/gpus/rtx3070.jpg',
  },
  {
    id: 'fake-3080',
    name: 'NVIDIA GeForce RTX 3080',
    vram_gb: 10,
    price_per_hour: 3,
    status: 'unavailable',
    image: '/images/gpus/rtx3080.jpg',
  },
  {
    id: 'fake-3090',
    name: 'NVIDIA GeForce RTX 3090',
    vram_gb: 24,
    price_per_hour: 4,
    status: 'unavailable',
    image: '/images/gpus/rtx3090.jpg',
  },
  {
    id: 'fake-4070',
    name: 'NVIDIA GeForce RTX 4070',
    vram_gb: 12,
    price_per_hour: 3,
    status: 'unavailable',
    image: '/images/gpus/rtx4070.jpg',
  },
  {
    id: 'fake-4080',
    name: 'NVIDIA GeForce RTX 4080',
    vram_gb: 16,
    price_per_hour: 4,
    status: 'unavailable',
    image: '/images/gpus/rtx4080.jpg',
  },
  {
    id: 'fake-4090',
    name: 'NVIDIA GeForce RTX 4090',
    vram_gb: 24,
    price_per_hour: 5,
    status: 'unavailable',
    image: '/images/gpus/rtx4090.jpg',
  },
  {
    id: 'fake-a5000',
    name: 'NVIDIA RTX A5000',
    vram_gb: 24,
    price_per_hour: 4,
    status: 'unavailable',
    image: '/images/gpus/rtxa5000.jpg',
  },
  {
    id: 'fake-6800xt',
    name: 'AMD Radeon RX 6800 XT',
    vram_gb: 16,
    price_per_hour: 3,
    status: 'unavailable',
    image: '/images/gpus/rx6800xt.jpg',
  },
  {
    id: 'fake-7900xtx',
    name: 'AMD Radeon RX 7900 XTX',
    vram_gb: 24,
    price_per_hour: 4,
    status: 'unavailable',
    image: '/images/gpus/rx7900xtx.jpg',
  },
];
